### ISSUE TITLE
Timeline & track

### ISSUE THREAD

**Issue by tonyketcham** [nbennett320/dawesome#5]
### Example case
Create a timeline with one track containing a sample offset from the beginning of the timeline

**Comment by nbennett320** [comment]
backend is implemented for this on PRs #13 and #14 🕺  (mostly 13)

**Comment by nbennett320** [comment]
Samples can be added, removed, moved between playlist tracks, and moved in terms of start time as of [this commit](https://github.com/nbennett320/dawesome/commit/b83e55024bbf9670b4a92fa4130e0a1680af48d4) 😄
