### ISSUE TITLE
Prettier is broken 

### ISSUE THREAD

**Issue by nbennett320** [nbennett320/dawesome#9]
<img width="869" alt="Screen Shot 2022-04-05 at 12 37 32" src="https://user-images.githubusercontent.com/42950788/161803479-c1ebdb3d-ac82-41d7-b996-0af9cc57332e.png">
Prettier is broken

**Comment by tonyketcham** [comment]
Prettier doesn't run on Rust files - https://github.com/nbennett320/dawesome2/blob/a5342cf244ba234973adcf500ff38651dda50513/.vscode/settings.json#L2-L4

Could it be another formatter in your IDE? I'm unfortunately not able to reproduce that issue
